Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -1,35 +1,166 @@
-# This is a basic workflow that is manually triggered
+description: >
+  Install Google's Chrome browser, for use in browser testing. Note:
+  only the latest stable release can be installed, as Google does not
+  maintain a public archive of previous releases. Supports Debian/Ubuntu
+  Linux, Alpine Linux (via Chromium), and macOS environments.
 
-name: Manual workflow
+parameters:
+  replace-existing:
+    type: boolean
+    default: false
+    description: >
+      If there is an existing installation of Google Chrome, replace it
+      with the latest stable release?
+  chrome-version:
+    default: latest
+    type: string
+    description: >
+      Version of Chrome to install, defaults to the latest stable release.
+      To install an older release, specify a full chrome version number,
+      e.g., 85.0.4183.83
+      Only supported on centos and debian
+      If replace-existing is false, this version is ignored.
 
-# Controls when the action will run. Workflow runs when manually triggered using the UI
-# or API.
-on:
-  workflow_dispatch:
-    # Inputs the workflow accepts.
-    inputs:
-      chrome-version:
-        description: |-
-          The Google Chrome/Chromium version to install and use.
-        default: latest
-        required: false
-      name:
-        # Friendly description to be shown in the UI instead of 'name'
-        description: 'Person to greet'
-        # Default value if no value is explicitly provided
-        default: 'World'
-        # Input has to be provided for the workflow to run
-        required: true
+steps:
+  - run:
+      name: Install Google Chrome
+      command: |
+        if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  # This workflow contains a single job called "greet"
-  greet:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+        CHROME_VERSION=<<parameters.chrome-version>>
+        # installation check
+        if uname -a | grep Darwin > /dev/null 2>&1; then
+          if ls /Applications | grep "Google Chrome" > /dev/null 2>&1; then
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-    # Runs a single command using the runners shell
-    - name: Send greeting
-      run: echo "Hello ${{ github.event.inputs.name }}"
+            <<#parameters.replace-existing>>echo "$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)is currently installed; replacing it"
+
+            HOMEBREW_NO_AUTO_UPDATE=1 brew uninstall google-chrome > /dev/null 2>&1 || true
+
+            $SUDO rm -rf /Applications/Google\ Chrome.app > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)is already installed"
+
+            exit 0<</parameters.replace-existing>>
+          else
+            echo "Google Chrome is not currently installed; installing it"
+          fi
+        elif cat /etc/issue | grep Alpine > /dev/null 2>&1; then
+          if command -v chromium-browser > /dev/null 2>&1; then
+
+            <<#parameters.replace-existing>>echo "$(chromium-browser --version)is currently installed; replacing it"
+
+            $SUDO apk del --force-broken-world chromium > /dev/null 2>&1 || true
+            $SUDO rm -f "$(command -v chromium-browser)" > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(chromium-browser --version)is already installed to $(which chromium-browser)"
+
+            exit 0<</parameters.replace-existing>>
+
+          else
+            echo "Google Chrome (via Chromium) is not currently installed; installing it"
+          fi
+        elif command -v yum > /dev/null 2>&1; then
+          if command -v google-chrome > /dev/null 2>&1; then
+            <<#parameters.replace-existing>>echo "$(google-chrome --version)is currently installed; replacing it"
+
+            $SUDO yum remove -y google-chrome-stable > /dev/null 2>&1 || true
+
+            $SUDO rm -f "$(command -v google-chrome)" > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(google-chrome --version)is already installed to $(which google-chrome)"
+
+            exit 0<</parameters.replace-existing>>
+          else
+            echo "Google Chrome is not currently installed; installing it"
+          fi
+        else
+          if command -v google-chrome > /dev/null 2>&1; then
+
+            <<#parameters.replace-existing>>echo "$(google-chrome --version)is currently installed; replacing it"
+
+            $SUDO apt-get -y --purge remove google-chrome-stable > /dev/null 2>&1 || true
+
+            $SUDO rm -f "$(command -v google-chrome)" > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(google-chrome --version)is already installed to $(which google-chrome)"
+
+            exit 0<</parameters.replace-existing>>
+          else
+            echo "Google Chrome is not currently installed; installing it"
+          fi
+        fi
+
+        # install chrome
+        if uname -a | grep Darwin > /dev/null 2>&1; then
+          brew update > /dev/null 2>&1 && \
+            HOMEBREW_NO_AUTO_UPDATE=1 brew install google-chrome > /dev/null 2>&1
+
+          echo -e "#\!/bin/bash\n" > google-chrome
+          perl -i -pe "s|#\\\|#|g" google-chrome
+          echo -e "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \"\$@\"" >> google-chrome
+
+          $SUDO mv google-chrome /usr/local/bin
+          $SUDO chmod +x /usr/local/bin/google-chrome
+
+          # test/verify installation
+          if google-chrome --version > /dev/null 2>&1; then
+            echo "$(google-chrome --version)has been installed in the /Applications directory"
+            echo "A shortcut has also been created at $(which google-chrome)"
+            exit 0
+          else
+            echo "Something went wrong; Google Chrome could not be installed"
+            exit 1
+          fi
+        elif command -v yum > /dev/null 2>&1; then
+          # download chrome
+          if [[ "$CHROME_VERSION" == "latest" ]]; then
+            CHROME_URL="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
+          else
+            CHROME_URL="https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-$CHROME_VERSION-1.x86_64.rpm"
+          fi
+
+          curl --silent --show-error --location --fail --retry 3 \
+            --output google-chrome.rpm \
+            $CHROME_URL
+          curl --silent --show-error --location --fail --retry 3 \
+            --output liberation-fonts.rpm \
+            http://mirror.centos.org/centos/7/os/x86_64/Packages/liberation-fonts-1.07.2-16.el7.noarch.rpm
+
+          $SUDO yum localinstall -y liberation-fonts.rpm \
+            > /dev/null 2>&1
+
+          $SUDO yum localinstall -y google-chrome.rpm \
+            > /dev/null 2>&1
+
+          rm -rf google-chrome.rpm liberation-fonts.rpm
+        else
+          # download chrome
+          if [[ "$CHROME_VERSION" == "latest" ]]; then
+            CHROME_URL="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
+          else
+            CHROME_URL="https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}-1_amd64.deb"
+          fi
+          curl --silent --show-error --location --fail --retry 3 \
+            --output google-chrome.deb $CHROME_URL
+
+          # Debian 10 fix
+          if grep -i buster /etc/os-release;then
+            $SUDO apt-get --allow-releaseinfo-change-suite update
+          fi
+
+          # The pipe will install any dependencies missing
+          $SUDO dpkg -i google-chrome.deb || $SUDO apt-get -fy install
+          rm -rf google-chrome.deb
+          $SUDO sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g' "/opt/google/chrome/google-chrome"
+        fi
+
+        # test/verify installation
+        if [[ "$CHROME_VERSION" != "latest" ]]; then
+          if google-chrome --version | grep "$CHROME_VERSION" > /dev/null 2>&1; then
+            :
+          else
+            echo "Something went wrong; Google Chrome could not be installed"
+            exit 1
+          fi
+        else
+          if google-chrome --version  > /dev/null 2>&1; then
+            :
+          else
+            echo "Something went wrong; Google Chrome could not be installed"
+            exit 1
+          fi
+          echo "$(google-chrome --version) has been installed to $(which google-chrome)"
+          echo "Chrome: $CHROME_VERSION" >> ${HOME}/.browser-versions
+        fi
